from . import manage_department
from . import manage_class
from . import manage_subject
from . import manage_academic_year
from . import registration
from . import clubs
from . import events_club
from . import res_partner
from . import leave
from . import exam
from . import exam_papers
from . import res_users